### ISSUE TITLE
Gratitude and feature request.

### ISSUE THREAD

**Issue by ghost** [ramonnr/AeroFanControl#2]
Thank you for such a wonderful facility for Linux. I would like to know whether you have a plan to **release GUI** soon?

**Comment by ramonnr** [comment]
A problem is that Linux is not an operating system. It's definitely possible to migrate to CMake (from qmake) and leverage CPack to output a .deb and .rpm to cover alot of bases, but there are other package managers that are equally relevant.
Currently I don't have the time to dig into it, at the end of March I should have more time / less job to do.

You can however build this yourself, on a debian system you need to install qtbase5-dev and build-essential.
Clone the repo and run
`qmake . && make -j`

**Comment by skrazee** [comment]
Thank you for the reply and sorry for being late. I might look into it. Thank you for the insight.
